### ISSUE TITLE
您是有兴趣修复由于pytdx导致的“公司信息详情”错误？

### ISSUE THREAD

**Issue by sidazhang123** [bopo/mootdx#10]
* Python version: 3.7
* Operating System: Windows 10

### Description
该问题于近2年前在[get_company_info_content获取某些F10信息不全](https://github.com/rainx/pytdx/issues/137) 提出且一直open，而在mootdx中依旧存在。看您刚刚更新过该部分，不知是否有兴趣修复，谢谢。

### What I Did

```
from mootdx.quotes import Quotes
client = Quotes.factory(market='std')
// “公司大事”返回None
print(client.F10(symbol='000001',name="公司大事")) 
// “关联个股”返回信息不全
print(client.F10(symbol='000001',name="关联个股"))
```

**Comment by bopo** [comment]
首先谢谢你对`mootdx`这个项目的关注和支持。这个问题我会放到日程里。我的技术很菜, 也希望多多提宝贵意见。

**Comment by sidazhang123** [comment]
这里有个严重问题：F10所基于的pytdx里的get_company_info_content是return content.decode('gbk')，会导致无法decode的byte在不报错的情况下return None，但其实是有byte data的。（在37000多的一个固定位置必有一个byte导致这个问题，即所有length>37000的页面，大约占50%-60%）
可以return content.decode('gbk','ignore')修正这个问题，但貌似无法override，只能改pytdx源码。

协议本身和最新客户端的抓包相比，request的几个byte不同了，但处理逻辑都没变，之前提到的截断问题（页底位置）可能能通过对应上这些byte修复吧，但影响不大就没细研究了。
