### ISSUE TITLE
实时获取数据的服务器问题

### ISSUE THREAD

**Issue by XavierXia** [bopo/mootdx#2]
你好，
请问一下
self.client = TdxHq_API(**kwargs)
self.bestip = os.environ.setdefault("MOOTDX_SERVER", '202.108.253.131:7709')

上面的代码中，这个server ip（202.108.253.131:7709）是怎么来的呢？
是自己架设的服务器还是券商还是通达信公版的行情服务器ip呢？

**Comment by bopo** [comment]
新版本已经修改了， 通过命令行 mootdx server -w 会自动写到配置文件 ~/.mootdx/config.json 里面
这样每次如果服务器失效了，可以测试找到最快的服务
