### ISSUE TITLE
client.minute(symbol='002028') 错误提示

### ISSUE THREAD

**Issue by DAMON10780** [bopo/mootdx#34]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-37-77bed4faa137> in <module>
      2 
      3 client = Quotes.factory(market='std')
----> 4 client.minute(symbol='002028')

d:\python\lib\site-packages\mootdx\quotes.py in minute(self, symbol)
    141         :return: pd.DataFrame
    142         '''
--> 143         with self.client.connect(*self.bestip):
    144             market = get_stock_market(symbol)
    145             result = self.client.get_minute_time_data(market=market, code=symbol)

AttributeError: __enter__

**Comment by bopo** [comment]
我来看看，会尽快解决

**Comment by bopo** [comment]
并没有问题，可能是服务器连接问题。

可以在命令行 运行 `mootdx bestip -v -w` 会自动为你选择最快的服务器
