### ISSUE TITLE
可转债历史数据获取识别

### ISSUE THREAD

**Issue by thereheis** [bopo/mootdx#47]
我发现一部分可转债 113 开头的 ， 使用get_k 是获取不到历史日线的 ， 
client.k(symbol="113569", begin="2020-06-03", end="2020-06-10")
而110 或者12 开头的可转债是正常的。  不知道是我调用的问题 还是 本身的bug .

**Comment by thereheis** [comment]
我看了一下code , 应该是 pytdx 的问题，  113开头应该是新开的字段， pytdx 没有更新， 
改一下 pytdx/hq.py  line 154

if code[0] in ['5', '6', '9'] or code[:3] in ["009", "126", "110", "201", "202", "203", "204"]:  
加上‘113’ 就可以了

**Comment by bopo** [comment]
好的，谢谢你的回复

**Comment by bopo** [comment]
因 pytdx 已经不再开发，我准备想把pytdx合并到本项目中

**Comment by bopo** [comment]
新版本已经解决
