### ISSUE TITLE
AttributeError: __enter__

### ISSUE THREAD

**Issue by 280185386** [bopo/mootdx#48]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-df768cb7190c> in <module>
      1 # 指数
----> 2 client.index(symbol='000001', frequency=9)

C:\Anaconda3\envs\assistant\lib\site-packages\mootdx-0.3.21-py3.6.egg\mootdx\quotes.py in index(self, symbol, market, frequency, start, offset)
    336         :return: pd.dataFrame or None
    337         '''
--> 338         with self.client.connect(*self.bestip):
    339             result = self.client.get_index_bars(int(frequency), int(market),
    340                                                 str(symbol), int(start),

AttributeError: __enter__

**Comment by bopo** [comment]
先是否做好了配置文件？ 命令行运行 mootdx bestip -w

然后查看网络是否有问题。我这里测试是好的
